# Generated by Django 5.1.5 on 2025-02-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20230708_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='joining_date',
            field=models.DateField(db_column='joining_date', null=True),
        ),
    ]
